// Generated by CoffeeScript 1.3.3
(function() {
  var Logger, colors, _;

  _ = require('underscore');

  colors = require("colors");

  Logger = (function() {

    function Logger(prefix) {
      var _this = this;
      this.prefix = prefix != null ? prefix : '';
      _.each(this._levels, function(name) {
        return _this[name] = function() {
          return _this._log.apply(_this, [name].concat(_.toArray(arguments)));
        };
      });
    }

    Logger.prototype._levels = ['error', 'warn', 'info', 'debug'];

    Logger.prototype._colors = ['red', 'yellow', 'cyan', 'grey'];

    Logger.prototype._pad = function(str) {
      var level, max, _i, _len, _ref;
      max = 0;
      _ref = this._levels;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        level = _ref[_i];
        max = Math.max(max, level.length);
      }
      if (str.length < max) {
        return str + new Array(max - str.length + 1).join(' ');
      }
      return str;
    };

    Logger.prototype._log = function(type) {
      var index;
      index = this._levels.indexOf(type);
      return console.log.apply(console, ["  " + this._pad(type)[this._colors[index]] + " - " + this.prefix.bold].concat(_.toArray(arguments).slice(1)));
    };

    return Logger;

  })();

  module.exports = {
    Logger: Logger
  };

}).call(this);
