// Generated by CoffeeScript 1.3.3
(function() {
  var argv, jbha, sys;

  sys = require("sys");

  argv = require("optimist").usage("Mark accounts for migration if they were last updated before a given date.").alias('d', 'date').describe('d', "Date up to which all all accounts will be marked as needing to migrate").demand('d').argv;

  jbha = require("./jbha");

  process.stdout.write("WARNING! This operation will affect the database. Continue? [y/n]: ");

  process.openStdin().once("data", function(data) {
    if (data.toString()[0] === "y") {
      return jbha.Client._migrationize(argv.d, function(err, numAffected) {
        if (err) {
          console.log("ERROR: " + err);
        } else {
          console.log("Success: " + numAffected + " accounts marked for migration.");
        }
        return process.exit();
      });
    } else {
      return process.exit();
    }
  });

}).call(this);
