// Generated by CoffeeScript 1.4.0
(function() {
  var AccountSchema, AssignmentSchema, CourseSchema, mongoose;

  mongoose = require('mongoose');

  AccountSchema = new mongoose.Schema({
    _id: String,
    nickname: String,
    is_new: {
      type: Boolean,
      "default": true
    },
    firstrun: {
      type: Boolean,
      "default": true
    },
    details: {
      type: Boolean,
      "default": false
    },
    migrate: {
      type: Boolean,
      "default": false
    },
    updated: {
      type: Date,
      "default": new Date(0)
    }
  }, {
    strict: true
  });

  CourseSchema = new mongoose.Schema({
    owner: String,
    title: String,
    teacher: String,
    jbha_id: {
      type: String,
      index: {
        unique: false,
        sparse: true
      }
    },
    assignments: [
      {
        type: mongoose.Schema.ObjectId,
        ref: 'assignment'
      }
    ]
  });

  AssignmentSchema = new mongoose.Schema({
    owner: String,
    date: Number,
    title: String,
    details: String,
    jbha_id: {
      type: String,
      index: {
        unique: false,
        sparse: true
      }
    },
    archived: {
      type: Boolean,
      "default": false
    },
    done: {
      type: Boolean,
      "default": false
    }
  });

  module.exports = {
    Account: mongoose.model('account', AccountSchema),
    Course: mongoose.model('course', CourseSchema),
    Assignment: mongoose.model('assignment', AssignmentSchema)
  };

}).call(this);
