// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    MONGO_STAGING_URI: process.env.STAGING_URI || "mongodb://keeba:keeba@ds037647-a.mongolab.com:37647/godhavemercy",
    SESSION_SECRET: "asethabalana",
    VALID_USERNAME: "avi.romanoff",
    VALID_PASSWORD: "kakster96"
  };

}).call(this);
