// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    MONGO_PRODUCTION_URI: process.env.MONGOLAB_URI,
    MONGO_STAGING_URI: "mongodb://keeba:stagedevel@ds033767.mongolab.com:33767/keeba-staging",
    SESSION_SECRET: "asethabalana",
    VALID_USERNAME: "avi.romanoff",
    VALID_PASSWORD: "kakster96"
  };

}).call(this);
