// Generated by CoffeeScript 1.4.0
(function() {
  var Account, argv, colors, config, models, moment, mongoose, num_shown;

  colors = require("colors");

  mongoose = require("mongoose");

  moment = require("moment");

  config = require("./config");

  models = require("./models");

  Account = models.Account;

  mongoose.connect(config.MONGO_URI);

  argv = require("optimist").usage("Show recently active users.\nUsage: $0 -n [num]").alias('n', 'num').demand('n').describe('n', "Number of recently active users to show").argv;

  num_shown = argv.n;

  Account.find().sort('-updated').select('_id updated nickname').exec(function(err, docs) {
    var date, doc, name, nickname, showing, _i, _len, _ref;
    if (docs.length < num_shown) {
      showing = docs.length;
    } else {
      showing = num_shown;
    }
    console.log("Showing most recently active " + (String(showing).red) + " of " + (String(docs.length).red) + " accounts");
    _ref = docs.slice(0, +num_shown + 1 || 9e9);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      doc = _ref[_i];
      name = doc._id;
      nickname = doc.nickname;
      date = moment(doc.updated);
      console.log("\n" + name.bold + " (" + nickname + ")");
      console.log(date.format("» M/D").yellow + " @ " + date.format("h:mm:ss A").cyan + (" (" + (date.fromNow().green) + ")"));
    }
    return process.exit(0);
  });

}).call(this);
