// Generated by CoffeeScript 1.3.3
(function() {
  var jbha;

  jbha = require("./jbha");

  process.on('message', function(message) {
    if (message.action = "refresh") {
      return jbha.Client.refresh(message.token, message.options, function(err, res) {
        process.send([err, res]);
        return process.exit(0);
      });
    }
  });

}).call(this);
