// Generated by CoffeeScript 1.4.0
(function() {
  var jbha;

  jbha = require("./jbha");

  process.on('message', function(message) {
    if (message.action = "refresh") {
      return jbha.refresh(message.token, message.options, function(err, new_token, res) {
        process.send([err, new_token, res]);
        return process.exit();
      });
    }
  });

}).call(this);
